//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class AdminUser
    {
        public int SuId { get; set; }
        [Display(Name = "登录名")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string UserName { get; set; }
        [Display(Name = "密码")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Pwd { get; set; }
        [Display(Name = "级别")]
        public Nullable<int> role { get; set; }
    }
}
