//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Appraise
    {
        public int AppraiseId { get; set; }
        [Display(Name = "评价用户")]
        public Nullable<int> UserId { get; set; }
        [Display(Name = "评价商品")]
        public int ProductId { get; set; }
        [Display(Name = "评价内容")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Content { get; set; }
        [Display(Name = "评价等级")]
        [Required(ErrorMessage = "{0}是必填项")]
        public Nullable<int> Grade { get; set; }
        [Display(Name = "评价时间")]
        public Nullable<System.DateTime> RateTime { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
