//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.Orders = new HashSet<Orders>();
            this.Users1 = new HashSet<Users>();
        }

        public int DeliveryID { get; set; }
        [Display(Name = "用户编号")]
        public Nullable<int> UserId { get; set; }
        [Display(Name = "收件人姓名")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Consignee { get; set; }
        [Display(Name = "详细地址")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Complete { get; set; }
        [Display(Name = "手机号")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Phone { get; set; }

        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users1 { get; set; }
    }
}
