//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class OrdersDetail
    {
        public int DetailID { get; set; }
        [Display(Name = "订单编号")]
        public int OrdersID { get; set; }
        [Display(Name = "商品编号")]
        public int ProductId { get; set; }
        [Display(Name = "购买数量")]
        public int Quantity { get; set; }
        [Display(Name = "状态")]
        public Nullable<int> States { get; set; }

        public virtual Orders Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
