//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersDetail = new HashSet<OrdersDetail>();
        }
    
        public int OrdersID { get; set; }
        [Display(Name = "下单日期")]
        [Required(ErrorMessage = "{0}是必填项")]
        public System.DateTime Orderdate { get; set; }
        [Display(Name = "下单用户")]
        public Nullable<int> UserId { get; set; }
        [Display(Name = "订单总额")]
        public Nullable<decimal> Total { get; set; }
        [Display(Name = "收货地址")]
        public Nullable<int> DeliveryID { get; set; }
        [Display(Name = "收货日期")]
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        [Display(Name = "订单状态")]
        [Required(ErrorMessage = "{0}是必填项")]
        public Nullable<int> States { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetail { get; set; }
    }
}
