//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Appraise = new HashSet<Appraise>();
            this.Favorite = new HashSet<Favorite>();
            this.OrdersDetail = new HashSet<OrdersDetail>();
            this.Photo = new HashSet<Photo>();
        }
    
        public int ProductId { get; set; }
        [Display(Name = "商品名")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string Title { get; set; }
        [Display(Name = "商品分类")]
        [Required(ErrorMessage = "{0}是必填项")]
        public int CateId { get; set; }
        [Display(Name = "市场价格")]
        [Required(ErrorMessage = "{0}是必填项")]
        public decimal MarketPrice { get; set; }
        [Display(Name = "本站价格")]
        [Required(ErrorMessage = "{0}是必填项")]
        public decimal Price { get; set; }
        [Display(Name = "商品描述")]
        public string Content { get; set; }
        [Display(Name = "上架时间")]
        public Nullable<System.DateTime> PostTime { get; set; }
        [Display(Name = "商品库存")]
        [Required(ErrorMessage = "{0}是必填项")]
        public int Stock { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appraise> Appraise { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
    }
}
